{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "gh-action-exporter.fullname" . }}
  labels:
    {{- include "gh-action-exporter.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.fqdn }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            backend:
              serviceName: {{ include "gh-action-exporter.fullname" . }}
              servicePort: {{ $.Values.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.fqdn }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  {{- end }}
